# Welcome to Jekyll!
#
# Site settings
title: Binarygap Log
email: yuseungku@gmail.com
description: "한걸음 차근차근 걸어가며 그 간극을 메꾸듯이, 꾸준하고 성실하게 성장하는 Colin의 리서치 및 상상 계획서 블로그"
tagline: "Bridging the gap step by step"
baseurl: ""
url: "https://binarygap.com"
repository: Sunggu/sunggu.github.com
github: Sunggu
lang: ko

# SEO & Analytics
google_site_verification: "" # Google Search Console verification code
naver_site_verification: ""  # Naver Webmaster Tools verification code
google_analytics:

comments: false

author: Colin
author_bio: "무언가를 상상하고 리서치하며, 새로운 것을 설계하고 계획서로 써내려가는 과정을 즐깁니다."
author_pic: ""

paginate: 5
paginate_path: "/:num/"

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# Build settings
theme: null
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
permalink: /:title

theme_switcher: false

# Allows all pages to be put into `_pages` folder
# for easier navigation and better SEO.
collections:
  pages:
    output: true
    permalink: /:title

# Exclude from processing.
exclude:
  - ".jekyll-cache"
  - "Gemfile"
  - "Gemfile.lock"
  - "theme"
  - "sandbox"
  - "posts"
